spring:
  datasource:
    url: jdbc:mysql://localhost:3306/version_tracker_db?useSSL=false&serverTimezone=GMT&createDatabaseIfNotExist=true
    username: root
    password:
  application:
    name: versionTrackerService
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 1212

