

spring:
  datasource:
    url: jdbc:h2:mem:versionTrackerServiceDatabase
    username: rootUser
    password: securedPassword
  application:
    name: versionTrackerService
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 1212